export { default as Navbar } from "./Navbar";
export { default as Main } from "./main";
export { default as Product } from "./Products";
export { default as Footer } from "./Footer";
export { default as ProductCard } from "./ProductCard";
export { default as QuickViewModal } from "./QuickViewModal";
export { default as HomeProductsSection } from "./HomeProductsSection";
export { default as Hero } from "./Hero";
export { default as HomeCategoriesSection } from "./HomeCategoriesSection";